/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#004395',
        'on-secondary-fixed': '#00201d',
        'inverse-primary': '#bec6e0',
        'surface-variant': '#e0e3e5',
        'inverse-surface': '#2d3133',
        'surface': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f7f9fb',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e0e3e5',
        'on-secondary-fixed-variant': '#005049',
        'on-surface': '#191c1e',
        'primary': '#000000',
        'primary-container': '#131b2e',
        'surface-container-high': '#e6e8ea',
        'secondary': '#006a61',
        'surface-tint': '#565e74',
        'on-primary-container': '#7c839b',
        'surface-container': '#eceef0',
        'secondary-fixed': '#89f5e7',
        'on-error': '#ffffff',
        'outline': '#76777d',
        'on-surface-variant': '#45464d',
        'background': '#f7f9fb',
        'primary-fixed': '#dae2fd',
        'tertiary-fixed-dim': '#adc6ff',
        'outline-variant': '#c6c6cd',
        'surface-dim': '#d8dadc',
        'on-secondary': '#ffffff',
        'tertiary': '#000000',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#3f465c',
        'inverse-on-surface': '#eff1f3',
        'tertiary-container': '#001a42',
        'secondary-fixed-dim': '#6bd8cb',
        'on-tertiary-fixed': '#001a42',
        'primary-fixed-dim': '#bec6e0',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#d8e2ff',
        'on-tertiary-container': '#3980f4',
        'surface-container-low': '#f2f4f6',
        'secondary-container': '#86f2e4',
        'on-secondary-container': '#006f66',
        'error': '#ba1a1a',
        'on-primary-fixed': '#131b2e',
        'on-background': '#191c1e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        sm: '16px',
        gutter: '24px',
        xs: '8px',
        md: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        base: '4px',
        xl: '64px',
        lg: '40px',
      },
      fontFamily: {
        'display-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
      boxShadow: {
        card: '0 1px 2px rgba(0,0,0,0.02), 0 2px 4px rgba(0,0,0,0.03)',
        'card-hover': '0 4px 12px rgba(0,0,0,0.08)',
        modal: '0 20px 60px rgba(0,0,0,0.15)',
      },
    },
  },
  plugins: [],
}
